### ISSUE TITLE
Calling #to_a on a store collection returns an empty array, unless that collection has already been loaded

### ISSUE THREAD

**Issue by andrew-carroll** [voltrb/volt#102]
Using `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]`

Here, `store._foos.to_a` works because we load `store._foos` on the line immediately before, when we push to it.

    ➜ bundle exec volt c
    Volt 0.8.26
    [1] volt(#<Volt::Page>)> store._foos
    => #<Volt::ArrayModel:12855100 []>
    [2] volt(#<Volt::Page>)> store._foos << {bar: 'foo'}
    => #<Promise(12092500): nil>
    [3] volt(#<Volt::Page>)> store._foos.to_a
    => [{:bar=>"foo", :_id=>"1b10518d779c8d912cb0140c"}]
    [4] volt(#<Volt::Page>)> store._foos
    => #<Volt::ArrayModel:12855100 [<Volt::Model:12098340 {:bar=>"foo", :_id=>"1b10518d779c8d912cb0140c"}>]>
    [5] volt(#<Volt::Page>)> exit

However, in this new console session, it returns an empty array until we call `store._foos` by itself for the first time.

    ➜ bundle exec volt c
    Volt 0.8.26
    [1] volt(#<Volt::Page>)> store._foos.to_a
    => []
    [2] volt(#<Volt::Page>)> store._foos.to_a
    => []
    [3] volt(#<Volt::Page>)> store._foos
    => #<Volt::ArrayModel:16145800 [<Volt::Model:14582000 {:_id=>"1b10518d779c8d912cb0140c", :bar=>"foo"}>]>
    [4] volt(#<Volt::Page>)> store._foos.to_a
    => [{:_id=>"1b10518d779c8d912cb0140c", :bar=>"foo"}]

**Comment by dennym** [comment]
#86 related I guess

**Comment by ryanstout** [comment]
Ok, I updated the docs a bit to explain this: http://docs.voltframework.com/en/docs/store_collections.html

Check the section called "Reactive Loading"

Thanks
