### ISSUE TITLE
Flower-Power - meta framework: a bridge between Lotus and Volt

### ISSUE THREAD

**Issue by alexsun** [voltrb/volt#104]
Hello World

The problem is important in web development. This is my summary for more than 15 years of my experience on the web development: from ASP, PHP4, plain HTML, CSS without firebug, more than 5 years with Drupal, this is a great and complex CMS/Framework, now learning in Ruby and C.

This is not about blah-blah TODO.app on pure JS and fresh RIA (from Flash), or generation a flat single-page of html application with super-smart JS tools, that be a very good in maintainable. Analogs all of this I had ten years ago, with opacity - oh this buzzwords :)

NEED modern the framework, that need for each Web Developer, in the Ruby Community.

I hope you have a minute to consider a idea, goals and problems:

https://github.com/alexsun/Flower-Power/blob/master/README.md

This description draft, not structured. Meager English, with interpreter; (maybe later I will find time for study English grammar, forgive me)

plan in few days (weeks) add description, structure of goals and beautify with dummy examples of usage

I'm not want forking, pull two frameworks and do all in a solo, maybe have more better way?

any comments, critics, help, very welcome

[Lotus issue: Flower-Power](https://github.com/lotus/lotus/issues/150)

**Comment by ryanstout** [comment]
@alexsun I've been come around to making volt work with other frameworks (rails), but I'm not sure I understand your goal here.  (Sorry, might partly be the language barrier)  Are there things in volt that lotus has that you feel volt needs?  (Obviously a lot of things are still on our todo list)
