### ISSUE TITLE
<:user-templates:menu />

### ISSUE THREAD

**Issue by Hendrie91** [voltrb/volt#107]
Where is this code located and how can I modify it? I want to be able to add login/logout links and access the current users username/email for use in my view files. Any help is greatly appreciated. Thank you for your time.

**Comment by andrew-carroll** [comment]
All of the code for the user templates components can be found [in this repository](https://github.com/voltrb/volt-user-templates). If you'd just like to override the user template menu view, you can create a new `app/user-templates/views/menu/index.html`. For example with,
```html
# app/main/views/main/index.html
<:Body>
  <:user-templates:menu />

# app/user-templates/views/menu/index.html
<:Body>
  foo
```
then the rendered content of `app/main/views/main/index.html` will be `foo`.

**Comment by ryanstout** [comment]
@Hendrie91 let me know if @andrew-carroll 's answer doesn't answer it for you.  Thanks!
