### ISSUE TITLE
not seeing sourcemap

### ISSUE THREAD

**Issue by superchris** [voltrb/volt#109]
Volt looks really awesome, but so far I've not been able to see the ruby code for my controller in chrome debugger. I ran the app with MAPS=true turned on and while I see an __opal_source_maps__ that contains Opal stdlib source I don't see the sourcemaps for my volt controller, for example, just one big main.js file. Am I missing something? Are other people getting this to work?

**Comment by ryanstout** [comment]
@superchris sorry for the late reply.  The source map in the gem release version of volt was a little limited and only showed source maps for some parts of code.  I'm working right now actually to get the next gem release out the door, which will support source maps across the board.  Should be out this week.

**Comment by ryanstout** [comment]
I'll close once I get it out :-)

**Comment by pencilcheck** [comment]
:+1:

**Comment by artnikpro** [comment]
It seems that sourcemaps are not working again. I just installed a fresh version of Volt on OS X, and here is what I see in Chrome's Dev Tools http://take.ms/3xaLK . There's a whole bunch of folders like "corelib", "opal.rb" etc. with blank .rb files. And there is no any of my controllers or models :(

**Comment by ryanstout** [comment]
Are you running one of the pre-release versions?  I haven't pushed a full
gem release with it yet.

**Comment by artnikpro** [comment]
Probably no, I installed it with command "gem install volt"
$ volt --version 
Volt 0.9.4

**Comment by ryanstout** [comment]
You can install a pre-release gem of volt with ```gem install volt --pre```
 You may need to remove the previous versions first to get it to use that
version when you run the volt command.

**Comment by artnikpro** [comment]
It's working now! Thanks for help!

**Comment by ryanstout** [comment]
No problem.  Hopefully this weekend I'll get time to do a full gem release.

**Comment by denispeplin** [comment]
Getting `GET http://localhost:3000/__OPAL_SOURCE_MAPS__/volt/volt/app.map 404 (Not Found)` errors in my Chome browser console.
Volt version is 0.9.5.

**Comment by denispeplin** [comment]
Errors disappeared after I started volt with `MAPS=all volt s`

I think it is too deep inside documentation (I found it in "Debugging" section), it probably should be in Readme.
