### ISSUE TITLE
A better changelog format

### ISSUE THREAD

**Issue by bbatsov** [voltrb/volt#112]
How about adopting something [like this](https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md) for the changelog?
Seems way more informative to me.

**Comment by ryanstout** [comment]
We've been following this one: http://keepachangelog.com/  Is there something you don't like about it?

**Comment by bbatsov** [comment]
Have nothing against the format you referred to (except the sparse use of whitespace). On the other hand most releases so far have just an `added` section and inconsistent format of the individual changelog entries. 

Keeping track of more extensive info like related issues and authors makes it easier to peruse related discussions and get in touch with the authors if you need to. Anyways, your project, your rules.

**Comment by ryanstout** [comment]
@bbatsov yea, I'll try and include issue numbers and authors on there.  A lot of the things I've been working on recently aren't directly tied to issues.
