### ISSUE TITLE
Show interactions with mongo in the log

### ISSUE THREAD

**Issue by bbatsov** [voltrb/volt#114]
Being able to see the communication between volt and mongo directly in the log would be pretty useful during development.

**Comment by ryanstout** [comment]
Something like how rails logs sql?

**Comment by ryanstout** [comment]
Someone started working on task logging (which also shows some queries).  Its on master, but it still needs more works.

**Comment by bbatsov** [comment]
> Something like how rails logs sql?

Yep.

> Someone started working on task logging (which also shows some queries). Its on master, but it still needs more works.

Great!

**Comment by ryanstout** [comment]
This is out now.  Let me know if you think it needs improvement.  If I get more time, I'll probably do a custom logger, but right now it just uses the tasks logger.
