### ISSUE TITLE
Opal specs don't work

### ISSUE THREAD

**Issue by bbatsov** [voltrb/volt#117]
Where are run the specs the opal portion just hangs forever:

```
~/p/volt git:master ❯❯❯ bundle exec rake
--------------------------
Run specs in Opal
--------------------------
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:9999, CTRL+C to stop
TypeError: undefined is not an object (evaluating 'args[0]')

  /Users/bozhidar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/opal-rspec-0.4.0/vendor/spec_runner.js:17 in global code
```

No idea where this type error originates from.

Ruby 2.1.5, OS X Yosemite, phantomjs 2.0

**Comment by ryanstout** [comment]
Humm, this works on my machine.  (with same ruby, osx)  What version of volt are you running?

**Comment by bbatsov** [comment]
Trying to run the specs on the `master` branch of volt itself.

On 22 February 2015 at 23:51, Ryan Stout <notifications@github.com> wrote:

> Humm, this works on my machine. (with same ruby, osx) What version of volt
> are you running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voltrb/volt/issues/117#issuecomment-75464779>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by ryanstout** [comment]
Humm, still passing on my machine.  I wonder what's different.  (Passed on
travis also)

**Comment by ryanstout** [comment]
@bbatsov any ideas on this issue?  I can't duplicate.

**Comment by bbatsov** [comment]
Well, they still don't work for me and I haven't really had any time to dig deep into this.

**Comment by ryanstout** [comment]
Sorry, I think I missed that you were on phantomjs 2.0.  Unfortunately, I think there's a bug in phantom 2.0.  You can downgrade to 1.98 and it should work.  I'll chat with the opal guys and see if they know more about it.
