### ISSUE TITLE
ORM Documentation

### ISSUE THREAD

**Issue by dsmithco** [voltrb/volt#118]
I gave Volt a spin for the first time last night, and I really like what I see so far. I come from a Rails background and consider myself more of a "get it done" app developer with more experience on the front-end (which can be good and bad).

One thing I love about Rails is ActiveRecord. It's a thing of beauty. What's the ORM plan for Volt in handling relational models?

**Comment by KillaPL** [comment]
I would love to be able to use relational database as well. I don't trust mongo nearly as much as I trust postgresql.

**Comment by Ch4s3** [comment]
Issues #11 and #16 are about this issue precisely. Basically Ryan is still building out an API to allow you to hook up whatever data backend you want. I'm sure he'd appreciate some help if you're so inclined.

**Comment by ryanstout** [comment]
there's some more docs now at docs.voltframework.com  Let me know what's missing.  Also, yes, we're working on our "data provider api" to allow anyone to integrate an existing database.  Should be out before 1.0.
