### ISSUE TITLE
rake's executable on installation of volt gem, conflicts with my rbenv rake

### ISSUE THREAD

**Issue by leroyg** [voltrb/volt#122]
I get this error when installing the gem volt:

"rake's executable "rake" conflicts with /Users/workstation1/.rbenv/versions/2.2.0/bin/rake
Overwrite the executable? yN"

I am fairly new to Rails but didn't expect this and haven't seen this issue with other gems I've installed.

Thank you.

**Comment by wlads** [comment]
You can _safely_ rewrite the executable. Volt uses [Bundler](http://bundler.io). It will use the right version of the rake gem when using ``bundle exec volt ...`` 

By _safely_ I mean after installing the new executable of rake, running ``rake`` will still use the most recent version see:

```sh
gem list | grep rake
# rake (10.4.2)
rake --version
# rake, version 10.4.2
gem install volt
# install volt overwriting the executable
gem list | grep rake
# rake (10.4.2, 10.0.4)
rake --version
# rake, version 10.4.2
```

This will become a nasty bug if running ``volt new sample_project`` call's rake and your (_newer_) version has some incompatibility with that one required by the gem.

Inspecting Gemfile.lock after generating an app you will see that when prepended with ``bundle exec`` the rake version used by volt will be 10.0.4 as they expected.

Hope this helps!

**Comment by ryanstout** [comment]
Like @wlads said, you can overwrite if you want.  Volt doesn't use rake in project generation, and when you run rake inside of a project, you should use ```bundle exec```  Thanks!

**Comment by leroyg** [comment]
@wlads thank you very much and @ryanstout likewise - appreciate the help.
