### ISSUE TITLE
Model initialize override issue / name conflict?

### ISSUE THREAD

**Issue by lexun** [voltrb/volt#123]
I'm a little confused on why this is happening... A very specific scenario is producing an error that can be avoided by renaming a model or collection, or removing a method.

Every time I click submit to save the model, I get this error:

```
[ERROR] wrong number of arguments (2 for 0) (ArgumentError)
```

The stack trace is pointing me at the initialize method in the tweet class:

```ruby
class Tweet < Volt::Model
  field :from, String
  field :to, String

  def initialize
    super
    self.from = ''
    self.to = ''
  end
end
```

If I get rid of the initialize method, everything saves correctly but in the view my `Tweet` attributes each show up as a `Volt::Model`. Here is the controller for reference:

```ruby
class MainController < Volt::ModelController
  model :store

  def index
    new_tweet
  end

  def tweet
    page._tweet
  end

  def new_tweet
    page._tweet = Tweet.new
  end

  def submit
    store._tweets << tweet
    new_tweet
  end
end
```

I'd love to know what I should be doing differently to properly make those attributes default to empty strings, and how to override initialize without issues, however that's not the issue I want to bring attention to.

The strangest part of this that doesn't make any sense to me is that if I rename `store._tweets` to `store._tweats` or `store._items` (really anything else). There are no errors - everything saves as expected even with initialize still in there. Alternatively, I can rename the `Tweet` model to `Tweat` and once again everything works.

If I remove the override to `initialize` OR rename either the model or collection name - there are no issues. What could be causing this deadly combination? Any idea what the connection is?

**Comment by ryanstout** [comment]
So there's a few things going on here.  First is that plural attribute names are assumed to be references to other collections.  Second is that initialize gets used internally, you can override it, but it takes a few arguments that need to passed along to super:

```
def initailize(*args)
  super

  ... your code here ...
end

Give that a try and let me know if it works.

**Comment by lexun** [comment]
Man... I can't believe I did that. I even knew about the arguments lol. Just got my languages confused regarding how they're supposed passed along.

Thanks Ryan, that was it.
