### ISSUE TITLE
firefox with volt

### ISSUE THREAD

**Issue by barstuk** [voltrb/volt#125]
I have a connection error on every volt-ruby app in firefox, does anyone know why is it happening? http://postimg.org/image/f8sdviwbz/full/

**Comment by ryanstout** [comment]
I can't duplicate this, what version of firefox are you on?

**Comment by ryanstout** [comment]
Closing for now, let me know if your still having the issue and what version of firefox your on.  Thanks!

**Comment by barstuk** [comment]
I'm using firefox 37.0.1
Mozilla Firefox for Linux Mint
mint - 1.0
On chrome there is no such errors so it's only firefox issue. I guess it's only ff fault, so issue can be closed.

https://forums.meteor.com/t/the-connection-to-ws-localhost-3000-sockjs-569-pgh47ec6-websocket-was-interrupted-while-the-page-was-loading/164

**Comment by ryanstout** [comment]
@barstuk I redid the socket stuff for 0.9.1, so lets revisit then and see if it still doesn't work for you.

**Comment by barstuk** [comment]
on tag 'v0.9.1.pre2' it still doesn't work

**Comment by ryanstout** [comment]
@barstuk this is on an app your testing with?  Its strange others aren't having this issue.  Is it linux specific you think?

**Comment by barstuk** [comment]
Yes it was testing on my app. You have right, it's ff linux specific so I think that issue can be closed.

**Comment by ryanstout** [comment]
Has anyone found a work around for it?

**Comment by dfyx** [comment]
@ybur-yug might be able to help. As far as I know, linux is his primary platform.

**Comment by ybur-yug** [comment]
I've never encountered this but I am on Ubuntu and can try to replicate @dfyx 

Will look into it tonight.
