### ISSUE TITLE
Broken link in volt/docs/FAQ.md

### ISSUE THREAD

**Issue by byronformwalt** [voltrb/volt#128]
volt/docs/FAQ.md has a broken link to Readme.md

**Comment by ryanstout** [comment]
Fixed on git, the updated docs will get published with the permissions branch.

**Comment by byronformwalt** [comment]
Since, I’m much less experienced than you are at web development frameworks and Ruby, you might benefit from my perspectives as I re-read your book.  I downloaded the eBook format for using iBooks, and am taking notes on everything I don’t understand and had to explore on my own to figure out.  When I’m finished, I’m going to email you this compiled set of notes, because I’m sure you will be going back through to update the documentation once the new release comes out.
