### ISSUE TITLE
Security: No 'identical validator' for signup page

### ISSUE THREAD

**Issue by byronformwalt** [voltrb/volt#129]
lib/volt/models/validators does not currently support testing to see whether two passwords were identically entered at signup.  This may lead to a user inadvertently misspelling their password.

**Comment by ryanstout** [comment]
Lots of sites are no longer requiring a confirm field on the password (twitter, facebook, etc...)  I might add in an option to the user-templates to add it in.  Personally though I like not having one, it speeds up the signup process.  And if you type in the wrong password, you can do a password reset.  I'm going to close this for now.  Thanks.

**Comment by byronformwalt** [comment]
Ryan, you’re right about the identical password validation phasing out, but these sites do use account email confirmation to facilitate password resets.  I didn’t see in the permissions branch any type of password reset or email confirmation for the upcoming release, but it sounds like you already have those on your todo list.

**Comment by ryanstout** [comment]
Yea, password reset is on the todo list.  The user-templates stuff is
pre-release right now.
