### ISSUE TITLE
Usability: Incomplete protection against attempts to execute calls intended for server-side use only.

### ISSUE THREAD

**Issue by byronformwalt** [voltrb/volt#130]
As an example, refer to `volt/lib/volt/volt.rb`.

Both the server and the client are allowed to call `Volt.server?` or `Volt.client?`.  However, only the server should be allowed to call `Volt.root`, since `File` is inaccessible to the client.  If it is desirable to allow the client to call `Volt.root` then a task should be setup with a promise that conditionally executes if `Volt.client?` returns true.  Otherwise, a meaningful error should be passed back to the javascript console.  For security purposes, I recommend the latter approach.  There may be other cases where an error results when the client attempts to execute methods shared between the server and the client.

**Comment by byronformwalt** [comment]
Recommended implementation of `Volt.root`: 
```
    def root
      if self.client?
        raise "Security Exception (Volt.root): Attempted to execute file operation directly from client. " 
      end
      @root ||= File.expand_path(Dir.pwd)
    end
```

**Comment by ryanstout** [comment]
ok, I added this in, will go out in 9.1.  Thanks.
