### ISSUE TITLE
Better commit messages

### ISSUE THREAD

**Issue by bbatsov** [voltrb/volt#131]
I was going through the commit history and saw commit messages like:

* `WIP`
* `Tracking some bug`
* `beta4`

I've also noticed that the project is not employing a consistent style for the commit messages - pretty much every contributor uses a different style for those. Compare this with the [commit history of RuboCop](https://github.com/bbatsov/rubocop/commits/master).

I believe that all projects can benefit from more descriptive commit messages and a consistent style for them, so I'd like to propose adopting the widely respected guidelines suggested [here](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Maybe we can add a note about this in the `CONTRIBUTING.md`?

**Comment by ryanstout** [comment]
@bbatsov a lot of these are me.  I like to commit often, so I'll start squashing and merging commits before I push.  I think everyone else committing is better about it.  If we need to, we can add more to the CONTRIBUTING.md file, but I think I'm the main offender right now. :-)
