### ISSUE TITLE
Set version 0.0.4 for volt-user-templates

### ISSUE THREAD

**Issue by KillaPL** [voltrb/volt#133]
Currently 

    volt new

command installs volt in version 0.8.26 and volt-user-templates in latest, which right now is 0.0.6.

This causes a missmatch, because volt-user-templates depends on

    Volt.fetch_user method

which is not present in Volt 0.8.26. It works fine for volt-user-templates 0.0.4.

Should volt have this specified for working version? If anybody confirms it, I'll be happy to send a PR.

**Comment by ryanstout** [comment]
Closing since 0.9 is out.  This was just kind of a big mistake on my part.  I'll be extra careful next time to make sure it doesn't happen again :-)
