### ISSUE TITLE
Redirecting

### ISSUE THREAD

**Issue by KillaPL** [voltrb/volt#135]
Hello

Sorry if I'm spamming at this point, but I feel that these issues should be simple to implement, or at least explained.

I wanted to do a simple thing: On root route I want to redirect user to one url if logged in ( if Volt.user_id ), and to another if not logged in.

I found out the 

    go

method, which led me to try this:

    def index
      if Volt.user_id
        go "/chat"
      else
        go "/login"
      end
    end

However, I have a couple of problems/questions with this:

1. This doesn't seem to get executed if there is no underlying template for this path. Is this by design? 
2. If this code decides to go to /login page, it throws a lot of errors and makes the page unusable:

    IfBinding:433 error: #<NoMethodError: 'undefined method `use_username?' for <Volt::Model:254 {}>'>
    function (){var self = TMP_77._s || this;

        return self['$use_username?']()}
    page.js:13344 AttributeBinding Error: #<NoMethodError: 'undefined method `login' for <Volt::Model:254 {}>'>
    page.js:13344 AttributeBinding Error: #<NoMethodError: 'undefined method `password' for <Volt::Model:254 {}>'>

And when I try logging in:

    Uncaught NoMethodError: undefined method `do_login' for <Volt::Model:254 {}>

How can I go about implementing a simple redirect? This seems like a reasonable feature to have: )

**Comment by ryanstout** [comment]
This looks like a bug on my end also.  Fixing...

**Comment by KillaPL** [comment]
Oh. Is there anything I can do to help? I can push the repo to github.

**Comment by ryanstout** [comment]
@KillaPL I've got a fix for it already.  I'm trying to get a big release out today.

**Comment by KillaPL** [comment]
Ok then, I'll try the next version in that case.

**Comment by ryanstout** [comment]
This is fixed on master, will go out very soon.
