### ISSUE TITLE
[0.9.0.pre1] NoMethodError at / undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by KillaPL** [voltrb/volt#139]
I updated the volt version in my experiments to the recent pre1 and it blows up on any route.

This is the trace I receive:

    /home/killa/.rvm/gems/ruby-2.1.3/gems/volt-0.9.0.pre1/lib/volt/server/rack/http_resource.rb: in dispatch_to_controller
          controller_name = params[:controller] + '_controller'...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/volt-0.9.0.pre1/lib/volt/server/rack/http_resource.rb: in call
            dispatch_to_controller(params, request)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/volt-0.9.0.pre1/lib/volt/server/rack/index_files.rb: in call
            @app.call env...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb: in block in call
            return app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb: in each
          @mapping.each do |host, location, match, app|...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb: in call
          @mapping.each do |host, location, match, app|...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/showexceptions.rb: in call
          @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/volt-0.9.0.pre1/lib/volt/server/rack/quiet_common_logger.rb: in call
        status, header, body = @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/etag.rb: in call
          status, headers, body = @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/conditionalget.rb: in call
            status, headers, body = @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/volt-0.9.0.pre1/lib/volt/server.rb: in call
          status, headers, body = @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/content_length.rb: in call
          status, headers, body = @app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/builder.rb: in call
          to_app.call(env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/connection.rb: in block in pre_process
            response = @app.call(@request.env)...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/connection.rb: in catch
          catch(:async) do...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/connection.rb: in pre_process
          catch(:async) do...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.7/lib/eventmachine.rb: in call
              result = op.call...
    /home/killa/.rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.7/lib/eventmachine.rb: in block in spawn_threadpool
              result = op.call...

And this is the code I use: https://github.com/KillaPL/arch_app (however with the volt version at stable 0.8.26)

Am I doing something wrong, or is this a bug?

**Comment by KillaPL** [comment]
I tried setting controller on all routes, but it changes nothing,

    params[:controller]

Is still nil.

**Comment by ryanstout** [comment]
@KillaPL There's quite a few things you need to update to go from 0.8.x to 0.9.0.  I'm working on a simple upgrade guide.  For now you might want to check here: https://github.com/voltrb/volt/blob/master/CHANGELOG.md#changed

**Comment by KillaPL** [comment]
I see. I'll try to upgrade using these tips. Thanks.
