### ISSUE TITLE
store underscore collections inspect is not returning the right elements

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#143]
If you have a jobs collection, calling the following

`puts store._jobs` will return the one job model not the list of job models.

**Comment by ryanstout** [comment]
Sorry, can you clarify this one?  Is it that its not loaded yet because of reactive loading (see docs under store).

**Comment by pencilcheck** [comment]
```
store = $page.store

store._jobs << {
  title: 'Test'
}

puts store._jobs
```

outputs

```
Volt 0.9.0
including Capybara::DSL in the global scope is not recommended!
#<Job:0x007f8a7cc47bc0>
```

**Comment by ryanstout** [comment]
So I'm not sure what's going on here, but I can't duplicate.  When I output I get this:
#<Volt::Model:0x007fcbe53bc078>

(Which is the .to_s)

When I do .inspect, I get:
#<Volt::ArrayModel:70256850729020 not_loaded path:jobs [<Volt::Model:70256850493500 path:[:jobs, :[]] state:loaded {:title=>"Test", :_id=>"f4a1ede7e1070a7d29d8c86a"}>]>

Any ideas on how to dup?  Can you check on 0.9.1.pre2  Thanks!

**Comment by pencilcheck** [comment]
Sure, let me do it again on .pre2

**Comment by pencilcheck** [comment]
Just tried it on .pre3 and it is not printing anything anymore. I have to manually call .inspect to print this:
```
#<Volt::ArrayModel:70235303239400 not_loaded path:jobs []>
```
Which is also not correct since I have pushed a job in it it should at least show that job.
