### ISSUE TITLE
Validation is not run when a new model is pushed to store underscore collections, nor when it is in a buffer and called save!

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#144]
When running the script with runner command like so `bundle exec volt runner script.rb`

Validation such as unique constraint is not run.

Example code:
https://gist.github.com/pencilcheck/3f360878d3aba8805b6d

There will be multiple google companies records created running the script multiple times.

**Comment by ryanstout** [comment]
I think this is an issue with the unique validation, not validations themselves.  I'll check it out.

**Comment by chrisvfritz** [comment]
I'm still seeing this issue with the unique validator in v0.9.3.pre6. I just added `unique: true` to the todo list video example, so I think it should be reproducible.

**Comment by ryanstout** [comment]
@chrisvfritz you added ```uniq: true``` to the label field?  Can you paste in your model?

**Comment by ryanstout** [comment]
@chrisvfritz thanks, pushed a fix to master for this.

**Comment by chrisvfritz** [comment]
Excellent! I'm doing a Volt demo at our Ruby meetup tonight and I'll be sure to include developer responsiveness in the list of pros. :smiley:
