### ISSUE TITLE
Why do we have to manually require rubygem gems in runner script

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#147]
If I have included `pry-byebug` gem in the development group in the Gemfile, why do we have to manually require them in the runner script? Would volt runner include them for us like how rails does it?

E.g.
```
require 'rubygems'
require 'bundler/setup'
require 'pry-byebug'
```

**Comment by ryanstout** [comment]
@pencilcheck we don't auto-include gems.  This was a decision made for a few reasons.

1. It really really increases boot performance, especially on larger apps. (one of the biggest complaints I hear about rails)  Component gems included in dependencies.rb will have the parts in app included by default.
2. It makes it so unused code doesn't get loaded.

See here for more reasons: http://myronmars.to/n/dev-blog/2012/12/5-reasons-to-avoid-bundler-require

You can require everything in your Gemfile with ```Bundler.setup```
