### ISSUE TITLE
signup form issue

### ISSUE THREAD

**Issue by barstuk** [voltrb/volt#151]
I have one more question, am I wrong if I say that signup form is broken? When I already have an account and trying to sign up again with the same email there is two cases:
When I pass valid password it will log me in (I guess it's not valid because it's a signup form)
When I pass invalid password it will tell me, that password doesn't match ( I guess it should return error, that email is already used.)
http://oi59.tinypic.com/13ygpxe.jpg

**Comment by ryanstout** [comment]
This should be fixed on master now :-)
