### ISSUE TITLE
"File not found" every time the page reloads when a change is made

### ISSUE THREAD

**Issue by paulleader** [voltrb/volt#158]
Hi there. I'm new to Volt, I'm working through the Todo List tutorial in the docs, so I might have missed something obvious.

* Open http://localhost:3000
* Navigate to http://localhost:3000/todos to test the Todo features as they get added
* Change a file as instructed in the documentations
* The page is automatically reloaded but it just shows the error "File not found: /todos".
* To see the changes I have to go back to http://localhost:3000/ and then navigate to http://localhost:3000/todos from the menu.

Have I missed something, or is this something that is still being worked on? I'm pretty certain I've not skipped a step.

Thanks

p.s. Volt looks amazing so far. I think this is the first time I've been really excited by a framework since I first tried Rails back in the 2.x days.

**Comment by ryanstout** [comment]
@paulleader You need to restart the server.  The auto-reloading for that is what I'm working on this week actually.  I'll update the docs in the mean time.

**Comment by ryanstout** [comment]
Also, thanks!

**Comment by paulleader** [comment]
Hey Ryan, I don't seem to need to reload the server after changing a template file, but I do have to go back to the root and then navigate to /todos manually.

It seems to be a general issue with accessing any page that isn't the root directly. I can't load http://localhost:3000/todos directly, I have to get there from http://localhost:3000/ for it to work.

Is that the same issue?

By the way, I spotted a bug in the tutorial code, is the tutorial a Github project where I can correct it and send you a pull request?

**Comment by paulleader** [comment]
Ignore me, restarting seems to have sorted the issue, and I've found the docs repo :)

**Comment by ryanstout** [comment]
@paulleader no worries. Hopefully I can finish all of the code reloading stuff soon. Also the docs repo is at https://github.com/voltrb/docs   We use gitbook to render everything. It's all just github flavored mark down though. PR's on the docs are always welcome :-)

**Comment by paulleader** [comment]
Cool, I've sent you a pull request already. I'm working my way through the rest of the docs at the moment, so there might be more :)

Any objection to me extending the tutorial?

**Comment by ryanstout** [comment]
Paul,
   Extending it would be awesome!  Go for it.

Thanks,
   Ryan
