### ISSUE TITLE
Can't access container or dom_nodes from model controller

### ISSUE THREAD

**Issue by mathieul** [voltrb/volt#168]
Hello,

First of all thank you so much for this framework, it is so refreshing!

I'm trying to access a component container or DOM nodes from a model controller after action callback (`index_ready`) following the jQuery FAQ from the documentation (http://docs.voltframework.com/en/getting_help/can_i_use_jquery_or_other_dom_manipulating_js.html), but I can't seem to access it right.

i.e.:

```ruby
def index_ready
  node = self.container
  `console.log(node)`
end
```

When the callback runs it throws an error:

```
Error during render of template at main/main/index: #<NoMethodError: 'undefined method `container_node' for #<Volt::AttributeSection:0x1e4>'>  page.js:15432

"NoMethodError: undefined method `container_node' for #<Volt::AttributeSection:0x1e4>"
"   at OpalClass.$new (http://localhost:3000/assets/volt/page/page.js:3361:15)"
[...]
```

Trying to access the range of DOM nodes with `self.dom_nodes` triggers a similar error, but this time with `range`:

```
Error during render of template at main/main/index: #<NoMethodError: 'undefined method `range' for #<Volt::AttributeSection:0x1e4>'
```

I'm using 0.9.0 or 0.9.1.pre3. Am I accessing the component element(s) the wrong way?

**Comment by ryanstout** [comment]
Should work now, let me know if it doesn't.

**Comment by mathieul** [comment]
Thanks Ryan, your fix takes care of that error. But now as I change route within the same component and then back, this time I get a new error. Let me describe a bit more.

What I'm trying to achieve is to execute a jQuery plugin on the result of searching for a selector within the scope of the DOM node containing the component. I'm testing with a main component from a generated new volt application. There are 3 views (main, index, about) and a model controller with 2 routes.

In the model controller I have:

```ruby
    def index
    end

    def index_ready
      found = Element.find(container)
      %x{console.log(found);}
    end

    def about
    end
```

In `main.html`, `index.html` and `about.html` I have 2 tags declared: `<:Title>` and `<:Body>` (`main.html` tags including content from `index.html` or `about.html` using the `{{ view ... }}` helper.

When I load the page at the `/` route, all is now ok, the container DOM node is logged in the console. If I click on the about link which changes the route to showing `about.html` content all is good. But then if I click on the index link that tries to re-render the `index.html` view and execute the after ready callback, I get a new JavaScript error:

```
Error during render of template at main/main/index: #<NoMethodError: 'undefined method `container_node' for nil'>

NoMethodError: undefined method `container_node' for nil at OpalClass.$new (http://localhost:3000/assets/volt/page/page.js:3361:15)
at NilClass.<anonymous> (http://localhost:3000/assets/volt/page/page.js:3037:31)
at NilClass.Opal.defn.TMP_1 (http://localhost:3000/assets/volt/page/page.js:2440:19)
[...]
```

**Comment by mathieul** [comment]
I've just tested again, this time with the latest master version (d507385b02c9693429c23d269e9007f9d5416a5b) and all is good. Thanks!

**Comment by ryanstout** [comment]
@mathieul cool, thanks!
