### ISSUE TITLE
Slow iteration with nested .each loop in the view

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#175]
I'm iterating 100 objects in a collection in store in the view using the _jobs.each, somehow it takes forever to load them because in the backend it is adding listener to each object, 1 sec for each. Am I doing something wrong here?
oh, and btw there is a subcollections in each record, something like job._requirements.each inside the outer each loop. I wonder if that is also why it is slowing down the loading?

There are two issues here that I see.

1. Takes too long to render the view with only 2 level loops
2. .each is blocking the view so the website is not functional at all when looping through the collections

This is a serious issue that needs to be fixed.

**Comment by pencilcheck** [comment]
Most likely related to this: https://github.com/voltrb/volt/issues/152

**Comment by ryanstout** [comment]
Can you push up a repo for me to check out?  Thanks

**Comment by ryanstout** [comment]
Fixed the N+1 issue.  There's still a small performance issue with the template parsing binding locations, but I'm adding that to my enhancement list.
