### ISSUE TITLE
Can't save User Model buffer from existing users

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#195]
For reminders:

Password validation is run in buffer since it is empty on load, and since buffer save! validates all attributes password will be validated as empty.

There should be a way to specify when the password validation should not be run on certain conditions.

Made:
https://github.com/voltrb/volt/pull/193

But Ryan is going to work on a better full on block styled version. woohoo.

**Comment by ryanstout** [comment]
@pencilcheck Ok, I redid how passwords get stored in 0.9.4.pre2.  Give it a try, I'm pretty sure it will be fixed.  The default permissions have it so a user can only update his own user, so on the server you may need to do:

Volt.as_user(the_user_or_their_id) do
  user.password = ' ... '
end

^ note, we now setup a field for :password, so you can use it without _

Let me know if that works.  Thanks!
