### ISSUE TITLE
Can't bind to blur event

### ISSUE THREAD

**Issue by andrewhavens** [voltrb/volt#207]
I am trying to bind to the blur event, but it doesn't seem to be working.

    <textarea e-blur="add_todo">{{ page._new_todo }}</textarea>

@pencilcheck mentioned in Gitter:
> currently the event is all listen on body
> then the event is trigged into appropriate handler based on the target I think
> so blur event wouldn't work

I'm still pretty new to Volt, so I'm not sure how to resolve this issue.

**Comment by ryanstout** [comment]
I'll see if I can get blur working, for now try using e-focusout

**Comment by ryanstout** [comment]
This is fixed in 0.9.4.pre2.  Thanks!
