### ISSUE TITLE
Deployment in Puma

### ISSUE THREAD

**Issue by pasviegas** [voltrb/volt#21]
Hi, I was trying to deploy volt in Amazon's Elastic Beanstalk with puma and nginx, but it seems like that the base assets from volt where missing.

Am I doing something wrong?

Thanks

**Comment by ryanstout** [comment]
Puma support is here!  I just released a pre-release in 0.9.1.pre2  (gem install volt --pre)  It adds support for puma.  Docs coming soon.  More servers coming shortly also.

**Comment by vais** [comment]
@ryanstout :sparkles: :tada: :sparkles:
