### ISSUE TITLE
[Edited] Volt server hangs for 10 minutes, then loads

### ISSUE THREAD

**Issue by iandonovan** [voltrb/volt#214]
Hi gang,

I'm doing my first bit of work in Volt, and I ran into a minor hangup during installation. On Ruby 2.2.1, I was able to install the gem just fine. I installed mongodb via homebrew, and I set up the links to run it on login, then started mongo. I ran the volt server (both with and without `bundle exec`) and saw the snazzy ASCII art in my terminal, but `localhost:3000` would hang indefinitely when I tried to visit it. I waited a few minutes, but still nothing.

Restarting my computer fixed it, believe it or not. Mongo must have not been running correctly. Seeing that information in my browser -- "Could not connect to MongoDB" or something to that effect -- would've been very helpful.

Love the framework so far!

**Comment by iandonovan** [comment]
FOLLOWUP

Turns out this isn't a mongo thing! I think it's on Volt's end. It happened again this morning; here's a rundown:

I'm running Mac OS 10.10.3, Ruby 2.2.1, and installed mongo 3.0.3 through homebrew. Mongo is running just fine after following homebrew's post-install instructions (loading `launchctl`, etc.) I start the Volt server and see the ASCII logo, then navigate to http://localhost:3000 and see a hanging page. I left the server running while I debugged with @RickCarlino, only to find that after about 10 minutes, the page loaded.

Through no action of my own, my browser (Chrome 43, fwiw) loaded the page after about 10 minutes. Subsequent server shutdowns and startups can be loaded in a few seconds, as one would expect. The volt console runs just fine.

**Comment by ryanstout** [comment]
@iandonovan if you have time, could you jump in the gitter, might be easier to debug there.  Thanks!

**Comment by ryanstout** [comment]
I'm closing this for now.  If your able to duplicate again, please reopen.

**Comment by iandonovan** [comment]
@ryanstout good call, thanks for helping this weekend
