### ISSUE TITLE
use Foreman by default / running mongo by default 

### ISSUE THREAD

**Issue by StephenOTT** [voltrb/volt#228]
Would it make sense to use Foreman by default so the mongodb can be running by default?

Similar to meteor, the point is to have your base config up and running as fast as possible with minimal effort.  Currently to get the DB running you need to do several config items.

Thoughts?

**Comment by ryanstout** [comment]
Yea, though I would rather have the volt command just run mongo (or other database). Foreman might make things more complicated. We could probably just make a hit ignored db folder that we pass --dbpath to from mongo. Thoughts?

**Comment by StephenOTT** [comment]
I was thinking the same(making is more complicated).  I am trying to think of some benefits.
My initial thought is the running multiple process types?

**Comment by ryanstout** [comment]
Yea, it is easy enough in Ruby to start a child process and kill it when the parent is killed. I can add that when I get time.

**Comment by dfyx** [comment]
:-1:

It's not volt's job to run mongo for several reasons:

* In a production environment I want control over my database
* In a dev environment there might be multiple volt apps and I don't them to interfere
* In the near future volt might not even need mongo at all.

**Comment by dfyx** [comment]
That being said: having app templates (like rails does) might be useful.

**Comment by ryanstout** [comment]
@dfyx yea, I was thinking it would be implemented in the volt-mongo gem.  I think for onboarding though it's a nice thing to have. I was thinking it could have a flag to disable auto running it in dev. You make good points though. I'll think on it a bit more. I'm ask for some feedback on gitter.

**Comment by dennym** [comment]
-1 for the same reasons @dfyx mentioned. In addition to that: For the advantage of a "faster" start developing I lose the time when I go production and have to figure out how to remove certain features.

And every developer should be fine with setting up his prefered way of starting servers. I sometimes use foreman if I have a bigger setup running or in most volt cases now I just run the mongodemon manually.

**Comment by dfyx** [comment]
Another reason: when running volt in docker, I don't want to have mongo running in the same container.

**Comment by ryanstout** [comment]
Since I'm almost done with volt-sql and it will be the new default (using sqlite by default probably), I'm going to close this.
