### ISSUE TITLE
login and signup routes should be moved to volt-user_templates component?

### ISSUE THREAD

**Issue by StephenOTT** [voltrb/volt#229]
Noticed that the /accounts does not work in the default app, and looked at the routes and saw that the /singup and /login routes are still in the main component.  Should these not be moved to the user-templates component?

**Comment by StephenOTT** [comment]
such as this: https://github.com/StephenOTT/volt-user_templates/blob/master/app/user_templates/config/routes.rb

**Comment by ryanstout** [comment]
@StephenOTT I just updated this on master, I like having them in the generator so you can change them easier if you want.  I now have all of the routes in the generated routes file.  Closing this for now, it should go out in the next gem release.

**Comment by StephenOTT** [comment]
just playing around with the way that routes work, was there any thoughts on providing the ability to override routes using the main component for other components.

Example use case is your situation " I like having them in the generator so you can change them easier if you want."

You would be able to put the proper routes in the user-templates and if you want to override those routes you would put them in Main.

Testing this a little, i see that if you place a route in main that already exists in the user-templates component it acts like a redirect, when the user-template component acts are the final point.

Example: 
Main has the route:  `client '/dog', component: 'user_templates', controller: 'login'`
and user-templates has the route: `client '/login', component: 'user_templates', controller: 'login'`

If you go to `/dog` you are redirected to /login.

This done by design?
