### ISSUE TITLE
Code getting called twice bug

### ISSUE THREAD

**Issue by ylluminarious** [voltrb/volt#238]
On a Volt project, I ran into a problem where I was trying to call some component code on a page with the `_ready` callback. However, very strangely, it got called twice if I called the code on a controller. Even more strangely, this issue got fixed when I simply removed the `<:Title>` tag from the view connected with my controller.
[Here is an example project illustrating my issue.](https://github.com/ylluminarious/multiple_loads_volt)
[Here is the code that gets called twice.](https://github.com/ylluminarious/multiple_loads_volt/blob/master/app/main/controllers/main_controller.rb#L6-L9)
[And removing this code will solve the problem.](https://github.com/ylluminarious/multiple_loads_volt/blob/master/app/main/views/main/index.html#L1-L3)
As you can see, this is quite odd behavior and so I think this is some sort of bug with Volt.

**Comment by ryanstout** [comment]
@ylluminarious I thought this was maybe related to the MainController, but its not.  Still working to track it down.

**Comment by ryanstout** [comment]
@ylluminarious try master and let me know if it works.

**Comment by ylluminarious** [comment]
@ryanstout Thanks, this seems to have fixed the problem :)

**Comment by ryanstout** [comment]
No problem, thanks for the heads up :-)

**Comment by ylluminarious** [comment]
@ryanstout Darn it, I just realized that this issue is not fixed. I tested it out again today and found out that it is not working; the only reason I thought it was working before was that my example "game" was on the index page, which was being loaded with HTTP instead of the persistent connection. As soon as I clicked away onto another page on the site, and looked back on the index, the bug was there again. You can check it out on the example project so you can see for yourself.
Sorry for the false confirmation of a fix.
