### ISSUE TITLE
Cannot load such file -- celluloid/logger on Windows 8.1

### ISSUE THREAD

**Issue by fry1026** [voltrb/volt#241]
Hello,
I've just installed Volt under Win8.1, trying to follow the Todo-Tutorial.

When I run bundle exec volt server, I get the following error message (both with Volt 0.9.3 and 0.9.4.pre5):

Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
D, [2015-07-04T18:22:49.215953 #8404] DEBUG -- : Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]

C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen/internals/logging.rb:1:in `require': cannot load such file -- celluloid/logger (LoadError)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen/internals/logging.rb:1:in `<top (required)>'

        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen/listener.rb:11:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen/listener.rb:11:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen.rb:2:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.6/lib/listen.rb:2:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/server/forking_server.rb:5:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/server/forking_server.rb:5:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/server.rb:18:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/server.rb:18:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/cli.rb:63:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/cli.rb:63:in `server'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/lib/volt/cli.rb:134:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/bin/volt:4:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/volt-0.9.4.pre5/bin/volt:4:in `<top (required)>'
        from C:/Ruby21-x64/bin/volt:23:in `load'
        from C:/Ruby21-x64/bin/volt:23:in `<main>'

Any ideas?
F

**Comment by fry1026** [comment]
With 0.9.4, this issue is not occurring anymore.

**Comment by ryanstout** [comment]
Cool. Yea, we were able to remove the celluloid dependent. Closing.
