### ISSUE TITLE
load component routes

### ISSUE THREAD

**Issue by dancinglightning** [voltrb/volt#242]
So, i found myself something to do with volt :-)

And so i notice when i create a new project (which works great) i get user_template component.
I don't want it but agree with it being a good default.

Just noticed when removing it, the routes are one by one in the app route file.
Now if this were rails and user_template an engine, i could mount the engine at some point and
slurp all it's routes with one command. 
Which i think would be a nice feature. So i guess this is a feature suggestion (though for a feature that i don't use yet). 
Close at your discretion and get on with it the great work.
T.

**Comment by ryanstout** [comment]
@dancinglightning I'm planning to add a "mount" command so you can load in the routes from a component at a specific url.  Right now they just get mixed in to all of the routes.  (So components can specify routes).  But I want to change that.  Anyway, its on the todo list.

**Comment by dancinglightning** [comment]
well, that's just what i meant. 
good to hear.

**Comment by dancinglightning** [comment]
i guess since its on the list, it can go from here
