### ISSUE TITLE
*** Error in `/usr/bin/ld': corrupted double-linked list: 0x09763d50 ***

### ISSUE THREAD

**Issue by jpmermoz** [voltrb/volt#247]
Hi Ryan, I saw your video at the Ruby Conf and I loved it :)
I decided to go deeper with Volt instead other alternatives like Meteor, mostly because I love Ruby and this looks like a promising project.

I'm having an issue while configuring volt. After running:

volt new sample_project

I'm getting this error:

*** Error in `/usr/bin/ld': corrupted double-linked list: 0x09763d50 ***

An error occurred while installing rbnacl-libsodium (1.0.3), and Bundler cannot
continue.
Make sure that `gem install rbnacl-libsodium -v '1.0.3'` succeeds before
bundling.

I'm running Ubuntu 14.04 x64 and ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]
Any thoughts?

Btw I tried updating libsodium libraries for Ubuntu but I'm still getting the error.
Thanks!

**Comment by ryanstout** [comment]
@jpmermoz so if you don't have the library installed locally, the gem should build it for you.  So maybe its an issue with an out of date version of libsodium?  If your not using it for anything, can you try removing libsodium locally, then try removing the rbnacl-libsodium gem and reinstalling it?

**Comment by jpmermoz** [comment]
@ryanstout I didn't have libsodium installed at all. At first I thought I needed that library installed in order to use the gems, so I did it, but still got the error.

I ended up by removing both gems rbnacl and rbnacl-libsodium from the Gemfile. Am I going to loose any important feature of Volt?

Thanks

**Comment by ryanstout** [comment]
@jpmermoz the message bus encryption uses libsodium. If you remove it, there is another flag you need to disable in config/app.rb. If you have time I would like to figure out what's going wrong.

**Comment by jpmermoz** [comment]
@ryanstout yes of course... i'll add the gems again and try to figure out whats going on too
any other information I can give you in order to help you?

**Comment by jpmermoz** [comment]
I finally installed the gem successfully.

I did the following steps:

sudo apt-get remove binutils
sudo apt-get purge binutils
sudo apt-get update
sudo apt-get install binutils
sudo apt-get install build-essential

After than I ran gem install rbnacl-libsodium without any errors. I guess there was something wrong with my ubuntu libraries.
