### ISSUE TITLE
use CodeClimate coverage tool

### ISSUE THREAD

**Issue by dancinglightning** [voltrb/volt#253]
Just a suggestion: i use CodeClimate on most my projects (too)

I noticed it's set up for volt, but not the code coverage part of it. It's easy to add with one gem and 2 lines of code. The hard work is done with the travis integration, it runs (like coverall i suppose) on a travis run.

The reason i suggest this is that you get line by line coverage analysis. Also a percentage by class.
I usually sort by that percentage to see where i work on next. It's very motivating i find.
Also you have both the smells and coverage in the same tool.

So, give it a spin if you like.

**Comment by dennym** [comment]
Does it use simpelcov like coveralls.io?

**Comment by dancinglightning** [comment]
yes it seems so. but you install their gem

**Comment by ryanstout** [comment]
A PR for this would be great :-)  My big concern is just that we want to ignore opal only files (since there isn't a way to get coverage on those and I don't want it to look like we have terrible coverage because of it, for people evaluating using volt)

**Comment by dancinglightning** [comment]
I found out that files may be excluded (http://docs.codeclimate.com/article/166-exclusions), but that doesn't affect the test coverage.
Their reporting gem use simplecov, and so you're saying that won't work on those ruby files that have the opal platform check ? Probably right, so then better to close this

**Comment by ryanstout** [comment]
Yea, we can revisit later if thats ok.
