### ISSUE TITLE
Volt::ReactiveArray#[] does not return nil for out of bounds index

### ISSUE THREAD

**Issue by balmoral** [voltrb/volt#261]
The current code fails if index is out of bounds, unlike ruby array which will return nil.
Suggestion:
```
    def [](index)
      # Handle a negative index, depend on size
      index = @array.size + index if index < 0

     # NEED THIS
     return nil unless index < @array.size

      # Get or create the dependency
      dep   = (@array_deps[index] ||= Dependency.new)

      # Track the dependency
      dep.depend

      # Return the index
      @array[index]
    end
```

**Comment by ryanstout** [comment]
Won't @array return nil if it's out of bounds on that?  I'm on my phone, so I can check later.

**Comment by balmoral** [comment]
but it fails on `@array_deps[index] ||= Dependency.new`

**Comment by ryanstout** [comment]
Ah, I'll fix :-)

**Comment by ryanstout** [comment]
Ok, I still don't understand why this would fail.  Its doing ||=, so it will create one at the index.  Do you have some example code that is failing?

**Comment by vais** [comment]
@ryanstout well, setting an element out of bounds does work in both MRI and Opal, but you may or may not want this:
```
$ pry
[1] pry(main)> a = [1,2,3]
=> [1, 2, 3]
[2] pry(main)> a[42] ||= 4
=> 4
[3] pry(main)> a
=> [1,
 2,
 3,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 nil,
 4]
[4] pry(main)>
```
Also, returning `nil` if index < 0 is probably a good idea - and there's already a PR for that: https://github.com/voltrb/volt/pull/259/files

**Comment by ryanstout** [comment]
@vais Ruby arrays behave the same way.  Or am I missing something?

**Comment by vais** [comment]
@ryanstout yes, they behave the same way in Ruby and in Opal. My point is that you may not want this behavior in this particular case. I.e. you will end up with a bunch of nils filling the gap.

**Comment by balmoral** [comment]
@ryanstout you learn something every day :smile: I had no idea ruby padded an array out with nils if you set an element beyond its size.

I got a failure client side - so may be it's the Opal implementation. I was calling `#last` on empty array. Definitely failed at the ||=. Can reproduce if you need.

I think @vais has a point though - do you want @array_deps array to lose one-to-one correspondence to @array?

**Comment by ryanstout** [comment]
@balmoral Can you give me more info so I can duplicate?  (code would be good)  

Also for @vais    I think maybe I haven't explained the way its written as it is now.  I don't want to just return nil if its out of bounds, because we want the missing value to be reactive.  So if the value was out of bounds, but becomes in bounds (because someone sets it to a value), we want the out of bounds nil to reactively update inside of a watch!  So to make that work, we need to keep track of the deps even for out of bound indexes.

Perhaps however I should switch @array_deps to a hash, so it could be sparse.  Thoughts?

**Comment by ryanstout** [comment]
Also, sorry it took me a while looking at this to figure out what you were talking about :-)

**Comment by balmoral** [comment]
@ryanstout sorry my suggested fix above was wrong, but still an issue:

It's a simple failure which will happen any time you access `array.last` or `array[-n]` on an empty ReactiveArray or ArrayMode (or when `size - n` is less than 0).

My code is `page._charts.last` and I'm expecting it to return nil if the `_charts` array is empty.

Error on console is:

```
Uncaught IndexError: index -1 too small for array; minimum 0
```

and it occurs on the line 

```
      dep   = (@array_deps[index] ||= Dependency.new)
```

This happens because `index` remains negative after the preceding code

```
     # Handle a negative index, depend on size
      index = @array.size + index if index < 0 
```

and fails because it's trying to set a value at a negative index.

So maybe the patch should be

```
   return nil if index < 0
```

and this shouldn't interfere with the reactive logic you're handling.

**Comment by ryanstout** [comment]
@balmoral I just fixed this on master actually :-)  Please reopen if your still seeing issues.

**Comment by balmoral** [comment]
@ryansout my timezone keeps me a bit out of sync. As always, I appreciate the great service :smile:

**Comment by ryanstout** [comment]
@balmoral no problem.  Thanks for letting me know about the issue.  Should have a pre-release gem out soon.
