### ISSUE TITLE
Uncaught NameError: uninitialized constant Volt::HttpController

### ISSUE THREAD

**Issue by dennym** [voltrb/volt#262]
Setting up a simple HttpController show this error in the browser console.

```
module Main
  class WhateverController < Volt::HttpController
  end
end
```
#=> Uncaught NameError: uninitialized constant Volt::HttpController

**Comment by ryanstout** [comment]
Is it in the server folder under controllers?

**Comment by dennym** [comment]
That did the trick. Wasnt aware of this folder option.
