### ISSUE TITLE
volt precompile hits javascript_files

### ISSUE THREAD

**Issue by dangerousbeans** [voltrb/volt#265]
Running `volt precompile` raises ```volt/lib/volt/server/rack/index_files.rb:52:in `javascript_files': Deprecation: #javascript_files is deprecated in config/base/index.html, opal 0.8 required a new format. (RuntimeError)```

**Comment by ryanstout** [comment]
@dangerousbeans yea, I don't have this working yet on the 0.9.5 prereleases.  Its on my todo list.

**Comment by ryanstout** [comment]
Should be fixed on master
