### ISSUE TITLE
self.container and self.dom_nodes not working

### ISSUE THREAD

**Issue by dancinglightning** [voltrb/volt#266]
With the latest and a blank app i am trying to get access to nodes:
http://docs.voltframework.com/en/getting_help/can_i_use_jquery_or_other_dom_manipulating_js.html

Slightly different errors when trying in the action or a ready callback.

    def index
      puts self.container.class.name

Uncaught NoMethodError: undefined method `container_node' for nil

    def index_ready
      puts self.container.class.name

Uncaught TypeError: self.$container(...).$class is not a function
Does that mean the returned object is a js object, but i can't seem to get any info out, neither with ruby syntax nor backticks

The second case is pretty much the same for dom_nodes. But on the action, dom_nodes creates the error

Uncaught NoMethodError: undefined method `range' for nil

At glance i can't see tests for either, and unfortunately i wouldn't know how to write one.

**Comment by ryanstout** [comment]
Yea, looks like a bug. Any chance you can push a demo app with it failing. It works for me on my demo app.

**Comment by dancinglightning** [comment]
https://github.com/dancinglightning/dom_test

**Comment by ryanstout** [comment]
Thanks, should be able to get to this later today.

**Comment by dancinglightning** [comment]
just fyi: this is off course related to my hover/focus issue. Hover and focus i don't think bubble and i read the code that attaches to event handlers to body.
So i was trying to get my event handler on the container.

I just realized i have unique id's myself. I can dish those out as element id's and thus jquery any element i need. In other words i don't need this quick. Just in case you have other things to do :-)

**Comment by ryanstout** [comment]
Sorry, I originally read this wrong.   ```dom_nodes``` returns a javascript Range object.  See http://docs.voltframework.com/en/docs/getting_view_dom_nodes.html  You can't call normal ruby methods on it (since its JS)  Its easier to use .first_element which returns a DOM Node object.  Read the docs above and let me know if it still doesn't make since.  Thanks!

**Comment by dancinglightning** [comment]
I see you closed this, and i understand about the js issue.
But in the actual action the NoMethodError seemed to me to come before the .class actually got executed. So isn't that a bug. I didn't have the .class.name in the beginning, just added that for the puts, and still got the NoMethodError.

**Comment by ryanstout** [comment]
Ok, sorry, I assumed NoMethodError was related to it returning a range, let me check it out.

**Comment by dancinglightning** [comment]
Maybe if you double check (i'm working off my dodgy memory)

About the js issue: i had read that page. And it was in no way clear that i would get raw js objects back.
I am not sure how to work with those (ie it could be in the docs) and as i said i did try some methods with backticks that didn't work.
So a direct link to the js api and a ruby code example how to work with it would be nice. I'll chat about my other road.

**Comment by ryanstout** [comment]
Ok, the issue was that your calling those methods before the {action}_ready method.  I added a warning about it to volt in https://github.com/voltrb/volt/commit/38b298cc77659750a3d60480ecc2c41c11ab6997

**Comment by dancinglightning** [comment]
I'm almost certain i saw that self.container called in a show action in some example, another doc pr :-)

**Comment by ryanstout** [comment]
@dancinglightning yea, I might have messed that up.  Sorry.

**Comment by ryanstout** [comment]
Its not rendered at that point, so I can't return it.

**Comment by dancinglightning** [comment]
if you find the place i can fix it

**Comment by balmoral** [comment]
@ryanstout @dancinglightning I'm trying to access component nodes (via Webix JS ui library) in index_ready, assuming that the page is built. However the JS library can't find the components when called in index_ready. But I can find them later on a button click. Is this problem related to this issue? Or is there another callback after the page is rendered?

**Comment by ryanstout** [comment]
Is it possible the Webix library is running something after the document
ready event also?  The document should be ready and the component should be
rendered when index_ready is called.  Keep in mind, index_ready means the
associated index.html is rendered.  If the content is in another view, then
it would be {view_name}_ready  Sorry if I'm not being helpful.  If you have
an example project, I can take a look.

Thanks

**Comment by balmoral** [comment]
@ryanstout Definitely no need for apology - you're always very helpful. You put me on the right track. In my opal wrapper I had the component creation happening inside a webix.ready() call. Removed that and all works as it should :smile:  

When you say 'in another view' do you mean in a another component? Like `webix_ready`? Have not come across that in the docs. 

Thanks again

**Comment by dancinglightning** [comment]
@balmoral after getting this wrong i improved the docs https://github.com/voltrb/docs/pull/71
I think they are still not 100%, but maybe it helps.
At least i had trouble with what was being returned (browser dom node / ranges) but i still didn't put the exact link into the docs (may go over it later).
Also, even i wrote about native, i still don't fully understand it. But it looks promising and using that approach one should be able to remove all backtick js code if one wants, and not being a js person, i do want.
btw, nice chart app.

**Comment by balmoral** [comment]
@dancinglightning nice work on the docs - clarifies it well. 

I'm working on a few Opal and Volt wrappers for JS libraries. Highcharts was the first. I'm now doing Webix which is a pretty comprehensive UI framework. Like you I don't have much JS experience, but Native makes it all straightforward enough. First an Opal gem which does the Ruby-JS wrap, then a Volt component gem to add reactivity. Then no more backticks, just reactive Ruby!

**Comment by dancinglightning** [comment]
@balmoral Nice, does that mean there is a opal-highchart . I would have a rails app where i could give that a shot. Used flot up to now. But i can't use volt there.

btw did you find good docs on native? i haven't. In my experiments i contributed a little to opal-pixi with native stuff like https://github.com/orbitalimpact/opal-pixi/blob/512adbd4ddaea9dd1f25af0b704ade6fc4bec7ab/lib/opal/pixi/sprite.rb , quite sweet i thought.

From reading native source i got this idea that it wraps and unraps, but i never found anyone actually writing about it (certainly not in opalrb)

**Comment by balmoral** [comment]
@dancinglightning see https://github.com/balmoral/opal-highcharts and https://rubygems.org/gems/opal-highcharts (and there's also the volt equivalents). Only a first cut, but I think covers most Highcharts stuff.

There aren't any docs (on their todo list I think). So I used opal-pixi and other wraps as a guide. 

Let me know how you go. :smiley:

**Comment by dancinglightning** [comment]
Nice stuff!  will let you know, maybe some months though.
