### ISSUE TITLE
`go` is listed as deprecated, but `redirect_to` seems not to work

### ISSUE THREAD

**Issue by Qqwy** [voltrb/volt#268]
I am using Volt version 0.9.4, and in my view, have code like this
    
    <span e-click="redirect_to('/')">go back to the home page</span>

This does not seem to work. There is no error, but there also is no redirect. nothing happens at all.

    <span e-click="go('/')">go back to the home page</span>
   
works without problems however. (with the side note that `go` is listed as deprecated in the Console, and also in [this post on the Volt blog](http://blog.voltframework.com/post/117031476149/volt-090-is-here-and-its-amazing)

**Comment by RickCarlino** [comment]
Was there any reason you chose to use a `span` instead of an `a` tag? Out of the box, volt should be able to resolve routes using standard URLs.

**Comment by Qqwy** [comment]
There was not a special reason, except that I expected anchor tags to create a 'hard' page redirect (e.g. a new page request to the server, instead of using the JS History API and only updating the changed parts). Is Volt overriding by default what happens when someone clicks an internal link?

**Comment by ryanstout** [comment]
@Qqwy yea, volt intercepts link clicks.  I think the issue your seeing is with single quotes inside of double quotes.  I'll fix the parser.

**Comment by ryanstout** [comment]
@Qqwy can you try using \' \' inside of the attribute, or moving it into the controller?

**Comment by ryanstout** [comment]
Closing for now.  Feel free to reopen if that doesn't work.
