### ISSUE TITLE
Promise Method Forwarding for count/length/size

### ISSUE THREAD

**Issue by Qqwy** [voltrb/volt#269]
I believe it is very common in client-side code that we want to know how many entries there are in a certain collection (X posts, X new chat messages). Right now, the following code works using Promise Method Forwarding (this is [from the docs](http://blog.voltframework.com/post/117031476149/volt-090-is-here-and-its-amazing) ), but this only works for fields of a model, not on collections of models.

    store._items.first.then {|i| i._name }
    store._items.first._name

It would be great if the following substitution would also work:

    store._items.then {|items| items.size}
    store._items.size

(And the same for `#length`, which is an alias of `#size`. `#count` also provides the same functionality but can also be passed a block to count only entries that return true for this block)

**Comment by ryanstout** [comment]
works for me.  It returns a promise.

**Comment by Qqwy** [comment]
Yes, it does seem to work for size and count.
I was confused by this because it turns out that this technique only works when used directly inside of the view. I was attempting to do it inside of the ModelController.

I think that this issue can be closed.

**Comment by ryanstout** [comment]
@Qqwy it should work the same no matter where its used from (as long as its on the store collection)  Are you seeing it not work somehow?  If so how?

**Comment by ryanstout** [comment]
Fixed on master, thanks!
