### ISSUE TITLE
raw doesn't resolve promise in view like html_safe does

### ISSUE THREAD

**Issue by dennym** [voltrb/volt#275]
When using html_safe on a promise in the view like `{{ object._html.html_safe }}` It renders string as html. 
Using raw like `{{ raw object._html }}`  doesn't. It just prints out the promise itself.

Demo App, just click the button for adding a simple html snippet and then click an index number for seeing the difference.
https://github.com/dennym/html-safe-vs-raw

**Comment by ryanstout** [comment]
thanks for the demo app!  I pushed a fix to master.  Going to do a gem release soon.
