### ISSUE TITLE
Error after extended uptime

### ISSUE THREAD

**Issue by TheAustinSeven** [voltrb/volt#282]
On an Ubuntu system after I leave the app running for an extended period of time(a week or so) I get the following error:
![image](https://cloud.githubusercontent.com/assets/7809358/9533748/1a1a1a82-4ce2-11e5-968c-78bc17f6452e.png)

I have tested this and it is repeatable. I personally am running ruby 2.2.2 on ubuntu 14.04 and have tested this with the default app.

**Comment by ryanstout** [comment]
Is this in development mode?

**Comment by TheAustinSeven** [comment]
yes, I am currently in the process of starting a test for this in production

**Comment by ryanstout** [comment]
I suspect this won't happen in production. We currently use drb to communicate between the parent and child processes when using the "forking server", which runs in development to handle code reloading. Long term I'll probably replace drb. It sounds like this is drb related, but it might not be. Nothing worse than a bug that takes a week to duplicate. :-)

**Comment by TheAustinSeven** [comment]
Ok, I did not see the same issue, but rather a new one. I am rerunning to confirm, but it seems like there may be a memory leak big enough to bring down the application. If this is true, I will open up a new issue.

**Comment by TheAustinSeven** [comment]
There also may be an occasional issue with the webserver's HTTP parsing also in production. I will investigate further. :disappointed:

**Comment by ryanstout** [comment]
@TheAustinSeven thanks.  Maybe we need something to hammer the app with requests or something so we can test it.  (Though it would probably need to be using a real browser and running queries incase the leak is in there)

**Comment by TheAustinSeven** [comment]
Ok, I have an app up right now in production, you could probably use something like selenium to simulate the requests, but I'm not terribly familiar with that territory.

**Comment by TheAustinSeven** [comment]
Yep, it seems to be a memory leak. I opened an issue for that with #296

**Comment by ryanstout** [comment]
Closed with #296
