### ISSUE TITLE
subclasses of custom Model do not inherit custom ArrayModel

### ISSUE THREAD

**Issue by alexandred** [voltrb/volt#286]
This is easiest to demonstrate with the following example:

```
class StorageBase < Volt::Model
end

class StorageBases < Volt::ArrayModel
end

class Attachment < StorageBase
end
```
In this case, store.storage_bases is an instance of StorageBases but store.attachments is an instance of Volt::ArrayModel. The expected behaviour would be that store.attachments is an instance of StorageBases.

**Comment by ryanstout** [comment]
PR merged.  Thanks
