### ISSUE TITLE
Avoiding "flush in flash" message

### ISSUE THREAD

**Issue by mkamachi** [voltrb/volt#288]
I'm getting the message "Can't flush while in a flush" so many times.
After the message, buttons doesn't respond at all without showing any error message.

In lib/volt/reactive/computation.rb, Computation::compute! method sets @computing=true.
When @computation.call fails, @computation remain true.
It never get back to false. So single "fail" of compute! freezes all the system forever.
How about to add "ensure @computing=false"?
I'd like to recommend to put "rescue => err; puts err" around run_in block to quick awareness on something wrong with computation. (Actually it doesn't show enough messages to help debugging.)
I hope Volt get better.
Thanks.

**Comment by kevin-DL** [comment]
Does it  happen when you use a task? It my case that's what happens.

**Comment by ryanstout** [comment]
This should be fixed on master.  You should get good error messages now.
