### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by TheAustinSeven** [voltrb/volt#296]
I have a test application app up on a 512mb digital ocean droplet. This is the autogenerated volt app running in production mode. After 6 days of uptime with only a few requests per minute, the application was killed due to running over the memory limit:

![9-8-2015_voltmemoryleak_inproduction-ipblocked](https://cloud.githubusercontent.com/assets/7809358/9745522/57b7d412-5640-11e5-917c-9fd8eb5e1fb6.png)

This definitely smells like a memory leak. I will wait until someone decides if they need anymore information before I restart this. This is the second time the process has been killed due to the application running over the limit. If you need anymore details, feel free to ask.

**Comment by ryanstout** [comment]
@TheAustinSeven yea, I've seen the memory leak recently also.  I'll track it down asap.  Sorry about that.

**Comment by ryanstout** [comment]
@TheAustinSeven Ok, I fixed it finally. (on master)  Check it out to confirm, but on my machine ruby goes up to 210mb, then holds there.  (And there's some GC settings I think we could tweak to make it use less)  Please reopen if its still broke.
