### ISSUE TITLE
route not being activated when param changes

### ISSUE THREAD

**Issue by balmoral** [voltrb/volt#320]
I need to watch params in the show method of the controller in order for the show method to be called when a different product type is selected in the menu. Is this expected behaviour?
 
view (menu) link:
```
{{ product_types.each do |product_type| }}
  <li>
    <a href="/products/{{ product_type }}" >{{product_type }}</a>
  </li>
{{ end }}
```

routes entry:
```
client "/products/{{ product_type }}", controller: 'products', action: 'show'
```

controller method:
```
  def show
    -> do
      load_products(params._product_type)
    end.watch!
  end
```

**Comment by ryanstout** [comment]
@balmoral Someone just had a similar question here: http://stackoverflow.com/questions/33158964/volt-framework-routing-when-are-actions-invoked/33179061#33179061  Check out the answer on there.  Basically, you don't need to manually watch, you can usually just do the load via a method call and it will work.  The view binding only calls the action when the path passed into the view binding changes.  So in these cases you have to either invoke through a method (which the binding will retrigger when the data changes), or use .watch!

**Comment by balmoral** [comment]
@ryanstout got it - thanks for taking time to answer twice :smile: will close
