### ISSUE TITLE
Sequential Task

### ISSUE THREAD

**Issue by miguelalarcos** [voltrb/volt#333]
Is there a way to execute calls of a concrete task sequentially? Maybe it would be good to have something like ```Volt::SequentialTask```.

I have a task that updates a lot of objects and I need that this task executes sequentially. Maybe there's another option like a mutex, not sure.

**Comment by jfahrer** [comment]
@miguelalarcos You can chain promises to guarantee the order of execution. You could also split up your execution on multiple tasks and then call those tasks from "master" task. Tasks also return a promise so you can chain them. For example

```ruby
FirstTask.something(params).then do |result|
  SecondTask.soemthing(result)
end.then do |result|
  ThirdTask.something(result)
end.then do |result|
 ...
end.fail do |err|
 ...
end
```

**Comment by miguelalarcos** [comment]
Thanks for the answer. But I would like to have sequentially when calls come from different users.

**Comment by ryanstout** [comment]
@miguelalarcos maybe I'm not understanding your use case.  Are you saying you want it so if a task is called in multiple places at the same time it doesn't run at the same time?  (Currently there is a thread pool that lets multiple requests run at the same time)

**Comment by miguelalarcos** [comment]
Yes, I would like the calls to go to a queue and then being processed one at a time. Is it possible? I can explain detailed the use case...

**Comment by miguelalarcos** [comment]
If there's a thread pool, this should work, shouldn't it?
```ruby
require 'thread'
$semaphore = Mutex.new

class MovementTasks < Volt::Task
  def movement(thing, container, ...)
    $semaphore.synchronize {
      store._movements << Movement(...)
      # calculate aggregates and update containers
      nil
    }
  end
end
```

**Comment by ryanstout** [comment]
yea, putting things in a mutex will make it run sequentially.  In most cases though you should try making whatever code your running in the task thread safe, though thats not always easy :-)

**Comment by miguelalarcos** [comment]
thanks a lot

**Comment by ryanstout** [comment]
no problem
