### ISSUE TITLE
require a gem client side gives a sprocket error

### ISSUE THREAD

**Issue by miguelalarcos** [voltrb/volt#334]
In my Gemfile I've got:

```gem 'ruby-measurement'```

but when requiring (```require 'ruby-measurement'```) I've got this error:
```
Sprockets::FileNotFound at /
couldn't find file 'ruby-measurement' with type 'application/javascript'
```

I can require the gem in the task file with no problem. I'm doing something wrong? Sorry if this is an issue of Ruby instead of Volt.

**Comment by ryanstout** [comment]
@miguelalarcos you need to put the gem on the opal load path to require it on the client (for non-volt opal gems).  See here: http://docs.voltframework.com/en/getting_help/can_i_use_opal_gems.html  You can add something like: ```Opal.use_gem 'ruby-measurement'``` to your config/app.rb or one of your dependencies.rb file.

**Comment by miguelalarcos** [comment]
Good. But now I get:

```
RuntimeError: An error occurred while compiling: ruby-measurement/definitions/metric/length

Unexpected content in parsing stream `µm) ` :ruby-measurement/definitions/metric/length:11
Source: ruby-measurement/definitions/metric/length:11:19
  unit.convert_to(:µm) { |value| value * 10_000_000.0 }
~~~~~~~~~~~~~~~~~~^
```

But this is not Volt specific error. I'll investigate it. Thanks.
