### ISSUE TITLE
How can I use Volt with a Sinatra-REST-MySQL Backend

### ISSUE THREAD

**Issue by mrkaspa** [voltrb/volt#65]

**Comment by mrkaspa** [comment]
@ryanstout I still can't see this, are you going to support it?

**Comment by ryanstout** [comment]
@mrkaspa Sorry, this got lost in the backlog.  I can probably roll out the RESTModel stuff tomorrow.  Putting it on my "tomorow" todo list.

**Comment by mrkaspa** [comment]
@ryanstout cool because what I've seen about volt.rb is more like meteor.js and I'm lookign for something more like angular.js, I don't know if volt.rb can be used this way because I have a REST API and some process there so I can't use a mongodb only for my backend.

**Comment by ryanstout** [comment]
Great news!  This is finally out.  Check out the docs here: http://docs.voltframework.com/en/docs/http_controllers.html
