### ISSUE TITLE
.rb files included in config directory may not belong to volt

### ISSUE THREAD

**Issue by BlueUpton** [voltrb/volt#80]
Gems like Capistrano and Whenever use the /config directory for their configuration files, but volt attempts to load those files at runtime.  This can result in errors.

I looked at the rails code to see how they treat /config, and it appears that they only load the specific filenames associated with rails, ignoring the rest of the files in /config.

So far, it seems like /config/app.rb is the only file that needs to be loaded here: https://github.com/voltrb/volt/blob/master/lib/volt/config.rb#L67

Perhaps a hard-coded array of volt-specific config files could be fed into the .each method?  I would be happy to submit a PR that fits your design decision.

**Comment by ryanstout** [comment]
Check out the change, on master now, config/app.rb is loaded, then config/initializers/*.rb  (no longer is all of /config run at start)
