### ISSUE TITLE
Nested hash model does not persist

### ISSUE THREAD

**Issue by johnwahba** [voltrb/volt#82]
If you are in volt console and you execute the following code from the docs:
```    
    store._states << {name: 'Montana'}
    montana = store._states[0]
    montana._cities << {name: 'Helena'}
    montana._capital = montana._cities.last
```
`_capital` does not persist

**Comment by ryanstout** [comment]
This got fixed at some point :-)  Let me know if it doesn't work for you.  Thanks.
