### ISSUE TITLE
Bug when accessing collections

### ISSUE THREAD

**Issue by gentoid** [voltrb/volt#86]
Code in view
```html
<table class="table">
    {{ directories_to_scan.each do |dir| }}
        <tr><td>{{ dir }}</td></tr>
    {{ end }}
</table>
```
and in controller
```ruby
def directories_to_scan
  [:_music_paths, :_new_music_paths].map do |collection_name|
    collection = self.model.send(collection_name)
    collection.count
    collection.map { |path| path._name }
  end.flatten.sort
end
```
Here I need to call ```.count``` on Volt's collections, otherwise method ```directories_to_scan``` returns an empty array.

**Comment by dfyx** [comment]
I think this is (kind of) intended. Use promises to wait until the collection has been loaded.

**Comment by ryanstout** [comment]
@gentoid I'm still changing a few things around that should make this just work.  Sorry for the delay.

**Comment by ryanstout** [comment]
@gentoid Check out the docs on Reactive Loading at http://docs.voltframework.com/en/docs/store_collections.html

Yea, so you can use promises to wait out both loading, and return a new promise to the binding.

```ruby
def directries_to_scan
  promise = Promise.new.resolve(nil)

  [:_music_paths, :_new_music_paths].map do |collection_name|
    promise = promise.then do
      self.model.send(collection_name).fetch do |items|
        items.map {|path| path._name }
      end
    end
  end

  return promise.then {|val| val.flatten.sort }
end

Let me know if you want me to break this code down a bit, if your new to promises, it can be confusing.
```
