### ISSUE TITLE
DOM-based Cross-Site Scripting issue with reactive data binds

### ISSUE THREAD

**Issue by ChaosData** [voltrb/volt#89]
Hi,

On the Volt homepage (http://voltframework.com/), there is an example of "Attribute Bindings" (http://docs.voltframework.com/en/docs/attribute_bindings.html) that seems to place the contents of an input tag into a separate part of the page (that updates as the text in the field is changed). It appears that this functionality does not securely update the DOM when copying the value of the input tag into the thing it is bound to. At the bottom of however the update is implemented it is likely doing an assignment to the `innerHTML` of the bound element. Due to this, it is possible to inject HTML into the page by typing (/pasting/dragging/etc) text containing HTML into the field (or potentially anything using this type of functionality). This should be modified (if it is doing something simple like that) to instead assign to `innerText` so that the content gets escaped by the browser when set.

For example, the below text can be copied into such a field, and the page will inject the `img` tag and execute the content of the `onerror` attribute.
```
Hello<img src="fail" onerror="alert('Hello World!!')"/> World!
```

**Comment by ryanstout** [comment]
@ChaosData Good catch, I did plan on having html escaped by default.  The binding uses jquery under the hood to assign the text in content bindings.  Sorry, this was an obvious oversight on my end, fixing now.

**Comment by ryanstout** [comment]
@ChaosData pushed the fix, I'm going to try to get a new gem version out tomorrow.  Thanks a bunch!
